common: &common
  adapter: postgresql
  host: localhost
  password: canvas  # Replace with the password you set for the new role
  encoding: utf8
  username: your_new_role      # Replace with the new role name
  timeout: 5000
  prepared_statements: false
  use_qualified_names: true
  shard_name: public
  schema_search_path: "''"

production:
  <<: *common
  database: canvas_production

development:
  <<: *common
  database: canvas_development

test:
  <<: *common
  database: canvas_test
  shard1: canvas_test_shard_1
  shard2: canvas_test_shard_2
  test_shard_1: canvas_test_shard_1
  test_shard_2: canvas_test_shard_2
